# Gradle JVM args
org.gradle.jvmargs=-Xmx4g -Xms512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m

# Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.daemon.enable=false
kotlin.compiler.execution.strategy=in-process
systemProp.kotlin.daemon.enabled=false

# KAPT
kapt.use.worker.api=true
kapt.include.compile.classpath=false
